Integer and Float OPs bench
PPN-microbench/PPN-microbench pull request #15
Opened 2024-12-01 18:13 UTC by Hybanos

Includes a lot of changes and simplifications to the `IOPs` and `FLOPs` microbenches. Merging them in a single `Ops` class, using templates to decide computed types.

Many questions needs to be answered/discussed before merge (poke @dssgabriel):

## Result validation
The results I am getting are coherent with what i find on the net (~20 GFLOPs on my laptop's i5-1135G7), but differs quite a lot from other benchmarks run locally.
Specifically [FLFC's Phenominal-benchmark](https://github.com/FCLC/A-Phenominal-benchmark), which gives about 3 times as many FLOPs (or about 62G).
However, modifying `A-Phenominal-benchmark`'s assembly to have it more closely match this project once compiled, the differences narrow down and the results become what i would consider to be 'close enough'.

Consider the following asm for Integer OPs measurement:

PPN-microbench asm:
```asm
mov    %eax, -0x50(%rbp)
mov    -0x4c(%rbp), %edx
mov    -0x6c(%rbp), %eax
imul   %eax, %eax
add    %edx, %eax
mov    %eax, -0x4c(%rbp)
mov    -0x48(%rbp), %edx
mov    -0x6c(%rbp), %eax
imul   %eax, %eax
add    %edx, %eax
```
This yeilds about 27 GIOPs, but contains 3 `mov` for every 2 operation performed.

A-Phenominal-benchmark's asm:
```asm
add rdx, 1
add rdi, 1
add rsi, 1
add r11, 1
add r8, 1
add r9, 1
add r10, 1
```
This yields about 60 GIOPs, but doesn't have any `mov` instructions.
Moreover, **is it safe to assume that performing operations on different register automatically triggers a CPU's SIMD capabilities ?**

Modifying this asm to
```asm
add rax, 1
add rax, 1
add rax, 1
add rax, 1
add rax, 1
add rax, 1
add rax, 1
add rax, 1
```
brings the results down to a suspicious 27 GIOPs.

It's clear that there is an advantage to cherry-picking the assembly that benchmarks run on, but it isn't possible in our case for the sake of portability.
Should we acknowledge the fact that our `Ops` (and possibly more) benchmarks won't give the theoretical best results and move on, or push  them to the limit and find a way to compile to the exact assembly we want ?
There is also the option to write specific asm for every architecture out there but i'm pretty sure nobody wants to be doing that.

## SIMD
Speaking of SIMD, i have tried a few times to make it work with either openmp's `#pragma omp simd for` & co or GCC's macros but to no success. I don't know if the way i was using those solutions were faulty or if the kernels i'm trying to make them run on aren't good.

Openmp seemed very promising, allowing to really chose which loop should be SIMD-optimised and which shouldn't.

## Best output metric
We can show this benchmark's results in 2 ways:
 - Averaging the results of every run
 - Extracting the max of every run

As we are trying to find the max theoretical performance of a system, is it really relevant to  show the average of every run ?
Note; I am in favor of having as much info as possible in the future-final-reports and letting the users decide how they want to interpret them.

## Warmup runs
Quick testing shows that the first few runs of this benchmark often yield lower results than following ones, which is probably due to the CPU's boost speed taking a bit of time to ramp up. 
This is a problem if we average results over before outputting them to the user, but can be easily mitigated with a couple of warm-up runs before actually saving the results.
However only outputting the maxed results from all runs should prevent the need of such runs.

2024-12-02 09:07 UTC, dssgabriel requested changes
I will give some additional details in the main discussion so I can have the full description of the PR.

2024-12-02 09:07 UTC, dssgabriel commented on src/PPN-microbench/ops.cpp
> +            threads[k].join();
Consider using [`std::jthread`](https://en.cppreference.com/w/cpp/thread/jthread) to avoid having to manually join threads.

2024-12-02 09:07 UTC, dssgabriel commented on src/PPN-microbench/ops.cpp
> +        results[0][j] =
Similarly to using `high_resolution_clock` and `time_point`, consider using [`std::chrono::duration`](https://en.cppreference.com/w/cpp/chrono/duration) instead.

2024-12-02 10:56 UTC, dssgabriel commented
To start off, I am not fully convinced that it makes sense to merge IntOps and FLOPs into a single class, but let's see what results you're able to get once the requested changes are made.

### Results validation

> The results I am getting are coherent with what i find on the net (~20 GFLOPs on my laptop's i5-1135G7), but differs quite a lot from other benchmarks run locally.
Specifically [FLFC's Phenominal-benchmark](https://github.com/FCLC/A-Phenominal-benchmark), which gives about 3 times as many FLOPs (or about 62G).

Are you measuring FLOPS here? Also, is it FP32 or FP64?
Note that `A-Phenominal-benchmark` FLOPS benchmarks are all single-precision SIMD-based (custom SSE, AVX and AVX-512 assembly implementations). 3-4x better performance for `A-Phenominal-benchmark` seems small but plausible if your current code failed to vectorize. Have you enabled compiler optimizations (`CMAKE_BUILD_TYPE=Release` and `-march=native`)?

### IntOPS

> PPN-microbench assembly (AT&T syntax):
> ```asm
> mov    %eax, -0x50(%rbp)
> mov    -0x4c(%rbp), %edx
> mov    -0x6c(%rbp), %eax
> imul   %eax, %eax
> add    %edx, %eax
> mov    %eax, -0x4c(%rbp)
> mov    -0x48(%rbp), %edx
> mov    -0x6c(%rbp), %eax
> imul   %eax, %eax
> add    %edx, %eax
> ```

This weird codegen is most likely due to the source being `acc += 1 * 1`.
I think you shouldn't be passing `1` directly, but rather a random value -- nor using a constant `N_OPS` as the compiler can do lots of optimization if it knows these (e.g. like this: https://godbolt.org/z/jf1WWThbY).

> Moreover, **is it safe to assume that performing operations on different register automatically triggers a CPU's SIMD capabilities ?**

No, SIMD has nothing to do with using different _scalar_ registers. SIMD is using an entirely different set of instructions that explicitly manipulate vector registers: a single instruction (SI) operates on multiple data (MD). For instance, `vpaddq zmm0, zmm0, zmm0` is the AVX-512 equivalent of doing 8 independent scalar `add rXX, rXX`.

However, using **different registers** means that **operations are independent**, and that the CPU core may execute multiple of these instructions at the same time. In the following:
```asm
add rdx, 1
add rdi, 1
add rsi, 1
add r11, 1
add r8,  1
add r9,  1
add r10, 1
```
All `add` instructions could be executed simultaneously (provided you have enough execution units available) because they are all independent: there are no Read-After-Write -- aka RAW -- dependency between instructions.

In your code:
```asm
add rax, 1  ; (1)
add rax, 1  ; (2)
add rax, 1  ; (3)
...
```
By always using the `rax` register, you are introducing a data-dependency between subsequent instructions. Here, you are essentially doing the following:
```cpp
rax = rax + 1;  // (1)
rax = rax + 1;  // (2)
rax = rax + 1;  // (3)
...
```
Therefore, you cannot compute `(2)` before you are done executing `(1)` as its result is used in the computation of `(2)`: you have introduced a RAW dependency between `(1)` and `(2)` (as well as between `(2)` & `(3)`, etc.), which limits how many of the integer execution units available in your CPU you can _actually_ use at the same time to run your calculation.

### SIMD

If OpenMP's `omp simd` directive fails to vectorize the code even with optimizations enabled, you may consider using a portable SIMD library, such as:
- Google's [highway](https://github.com/google/highway)
- [Kokkos SIMD](https://kokkos.org/kokkos-core-wiki/API/simd/simd.html)
- Ecole Polytechnique's [xsimd](https://github.com/xtensor-stack/xsimd) (French!)
There are many more libraries of this kind in C++, look into them and pick what works best for you.

### Metrics

I share your opinion in that your tool should report as much information as possible. Regarding performance, I expect to have info about:
- minimum
- maximum
- average
- median
- error (i.e., the stability of your benchmark's results: may be reported as MAD, MAPE, MADE, etc.)

The metric you choose to report with the greatest "importance" is up to you, I am fine with either the maximum or the average/median (with error!).

### Warmup

You should absolutely add a warmup loop before your main benchmarking loop. Because the warmup loop should not be timed, you won't even have to deal with it when computing the results.

Example of what it should look like (using Martinus' nanobench terminology):
```cpp
for (auto w = 0; w < N_WARMUP; ++w) {
  // call bench function
}

for (auto e = 0; e < N_EPOCHS; ++e) {
  auto t1 = high_resolution_clock::now();
  for (auto i = 0; i < N_ITERATIONS; ++i) {
    // call bench function
  }
  auto t2 = high_resolution_clock::now();
  results[e] = duration(t2 - t1) / N_ITERATIONS;
}
```

2025-01-03 11:53 UTC, dssgabriel requested changes

2025-01-03 11:53 UTC, dssgabriel commented on include/PPN-microbench/_ops/ops.hpp
> +    // size_t **f64SIMDRes;
Why is this commented?

2025-01-03 11:53 UTC, dssgabriel commented on main/conductor_main.cpp
> +#include <iostream>
It does not seem like `iostream` is needed in this file, consider removing it.

2025-01-03 11:53 UTC, dssgabriel commented on src/PPN-microbench/_ops/ops.cpp
> +    results = new size_t *[6];
Why use `new`? A vector of static arrays is fine as the size of the elements are known at compile-time (it would be like having a vector of 6-fields `struct`s).

2025-01-03 11:53 UTC, dssgabriel commented on src/PPN-microbench/_ops/ops.cpp
> +        t1 = steady_clock::now();
Why use a `steady_clock` and not a `high_resolution_clock`?

2025-01-03 11:53 UTC, dssgabriel commented on src/PPN-microbench/CMakeLists.txt
> +        FILES ${PROJECT_SOURCE_DIR}/include/PPN-microbench/ops.hpp
A single `FILES` clause is enough:
```suggestion
        FILES
            ${PROJECT_SOURCE_DIR}/include/PPN-microbench/microbench.hpp
            ${PROJECT_SOURCE_DIR}/include/PPN-microbench/context.hpp
            ${PROJECT_SOURCE_DIR}/include/PPN-microbench/conductor.hpp
            ${PROJECT_SOURCE_DIR}/include/PPN-microbench/ops.hpp
```

2025-01-03 11:53 UTC, dssgabriel commented on CMakeLists.txt
> +set(CMAKE_BUILD_TYPE "Debug")
Do not set `BUILD_TYPE` by default, you should always check if it was set by the user first. Moreover, CMake already defaults to "Debug" if it isn't given a `BUILD_TYPE`.

2025-01-03 11:53 UTC, dssgabriel commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 20)
Setting the C++ standard this way is considered bad practice as it will also set it for all the dependencies that will be compiled alongside your project. Instead, use compile features on the relevant targets, e.g.:
```cmake
target_compile_features(PPN-microbench PRIVATE cxx_std_20)
```

2025-01-03 11:53 UTC, dssgabriel commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS_DEBUG "-Wall -Wextra -g -O3 -march=native -fopenmp")
Why are you enabling all optimizations in Debug?

Also, I am not convinced on setting flags through an env variable, it is generally considered bad practice. Instead, you should define an interface library that adds the relevant flags when linked to another target:
```cmake
add_library(PPN_microbench_flags INTERFACE)
if(CMAKE_BUILD_TYPE STREQUAL "Debug") 
   target_compile_options(PPN_microbench_flags INTERFACE -Wall -Wextra -g3)
else()
    target_compile_options(PPN_microbench_flags INTERFACE -march=native)
endif()

target_link_libraries(PPN-microbench PRIVATE PPN_microbench_flags)
```

Moreover, you should never explicitly pass `-fopenmp` but rather link against OpenMP (and of course, first check that it is an available dependency!):
```cmake
# NOTE: is it always required?
find_package(OpenMP)

target_link_libraries(PPN-microbench PRIVATE OpenMP::OpenMP_CXX)
```

2025-01-03 11:53 UTC, dssgabriel commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS_RELEASE "-O3 -march=native -fopenmp")
Same thing here. Also, adding `-O3` is redundant if CMake is compiling with `CMAKE_BUILD_TYPE=Release`, which enables it by default.

2025-01-03 11:53 UTC, dssgabriel commented on main/CMakeLists.txt
> +target_link_libraries(main PPN-microbench nlohmann_json::nlohmann_json )
Formatting change but why the final space?
Also, consider adding `PRIVATE` after `main` to indicate that these dependencies should not be forwarded to anything that depends on `main`.

2025-01-03 11:53 UTC, dssgabriel commented on main/CMakeLists.txt
> +target_link_libraries(conductor_main PPN-microbench nlohmann_json::nlohmann_json )
Same thing here.

2025-01-03 11:53 UTC, dssgabriel commented on main/conductor_main.cpp
> +#include <PPN-microbench/ops.hpp>
Twice the include?

2025-01-03 11:53 UTC, dssgabriel commented on src/PPN-microbench/ops.cpp
> +        // acc[15] += val;
Consider removing these comments.

2025-01-03 16:04 UTC, Hybanos commented on CMakeLists.txt
> +set(CMAKE_CXX_FLAGS_DEBUG "-Wall -Wextra -g -O3 -march=native -fopenmp")
The behavior of the app changes a lot between Release and Debug, i got stuck a few times trying to have converging results on both types.
I figured it would make it a lot easier if we have similar optimisations for all build types and guarantee the same behavior. 

I'm struggling to understand the purpose of having two different build types (I know it's integrated in cmake by default but still, why force ourselves using it), especially when we are working with very fine compilation issues.

2025-01-03 18:23 UTC, Hybanos commented on CMakeLists.txt
> +set(CMAKE_BUILD_TYPE "Debug")
after a bit of investigation i don't think that's really really true. By default (without specifying `-DCMAKE_BUILD_TYPE=Debug` ), the `CMAKE_BUILD_TYPE` env variable is set to `""`

2025-01-03 18:38 UTC, Hybanos commented
> Also, I am not convinced on setting flags through an env variable, it is generally considered bad practice. Instead, you should define an interface library that adds the relevant flags when linked to another target:

I couldn't figure out to make the interface library work, but i still implemented an if statement to set the flags based on the build type.
```cmake
if(CMAKE_BUILD_TYPE STREQUAL "Debug" OR CMAKE_BUILD_TYPE STREQUAL "")
    target_compile_options(PPN-microbench PRIVATE -Wall -Wextra -g3 -O3 -march=native)
else()
    target_compile_options(PPN-microbench PRIVATE -march=native)
endif()
```

2025-01-04 17:12 UTC, dssgabriel commented
@Hybanos
> I couldn't figure out to make the interface library work, but i still implemented an if statement to set the flags based on the build type.
>
> ```cmake
> if(CMAKE_BUILD_TYPE STREQUAL "Debug" OR CMAKE_BUILD_TYPE STREQUAL "")
>     target_compile_options(PPN-microbench PRIVATE -Wall -Wextra -g3 -O3 -march=native)
> else()
>     target_compile_options(PPN-microbench PRIVATE -march=native)
> endif()
> ```

Why are you enabling optimization flags to the "Debug" and default builds of your project? Optimization should never be able unless explicitly requested by the user through `CMAKE_BUILD_TYPE=Release`.

2025-01-05 01:12 UTC, Hybanos commented
> Why are you enabling optimization flags to the "Debug" and default builds of your project?

From the testing i've done, `-O3` is mandatory for simd vectorisation, either from the compiler or OpenMP. I could add more `#pragma GCC optimize()` directives but in my opinion ([as explained here](https://github.com/PPN-microbench/PPN-microbench/pull/15#discussion_r1901935125)) it's easier to have everything everywhere in `O3` and only push `O0` when absolutely needed. Tell me if it's the wrong approach tho.

2025-01-05 10:35 UTC, dssgabriel commented
I would rather have the reversed approach, i.e. ensure that the SIMD version has `-march=native -O3` pushed when compiling it. Moreover, it's not the purpose of a Debug build to check code generation (your tool is not meant to be _used_ in Debug mode).

Also, which version of GCC are you using? Vectorization flags are enabled by default in `-O2` (thus included in `-O3`) since GCC v12.0.
Does pushing these `pragma`s also work with LLVM toolchains? You need to think about this for portability purposes.

2025-01-07 09:59 UTC, dssgabriel approved these changes

2025-01-07 10:17 UTC, Hybanos commented
Ok, those changes are implemented. There is still the [issue](#23) about GCC compiler macros but this is for another day.

2025-01-07 10:20 UTC, merged